# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  incrivelhistoria.com.br:
    site_hosts:
      - canonical: incrhist.test
        redirects:
          - www.incrhist.test
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: dsemblano@gmail.com
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
