---
- name: Require manual definition of remote-user
  fail:
    msg: |
      When using `--ask-pass` option, use `-u` option to define remote-user:
      ansible-playbook server.yml -e env={{ env | default('production') }} -u root --ask-pass
  when: ansible_user is not defined and cli_ask_pass | default(false)

- name: Check whether Ansible can connect as root
  local_action: command ansible {{ inventory_hostname }} -m raw -a whoami -u root {{ cli_options | default('') }}
  failed_when: false
  changed_when: false
  check_mode: no
  register: root_status
  tags: [connection-tests]

- name: Set remote user for each host
  set_fact:
    ansible_user: "{{ ansible_user | default(('root' in root_status.stdout_lines) | ternary('root', admin_user)) }}"
  check_mode: no

- name: Announce which user was selected
  debug:
    msg: "Note: Ansible will attempt connections as user = {{ ansible_user }}"

- name: Load become password
  set_fact:
    ansible_become_pass: "{% raw %}{% for user in vault_users | default([]) if user.name == ansible_user %}{{ user.password | default('') }}{% endfor %}{% endraw %}"
  when: ansible_user != 'root' and not cli_ask_become_pass | default(false) and ansible_become_pass is not defined
  no_log: true
